// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protocs/loan.proto

package packets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoanClient is the client API for Loan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanClient interface {
	CreateLoan(ctx context.Context, in *InputCreateLoan, opts ...grpc.CallOption) (*OutputCreateLoan, error)
	GetLoans(ctx context.Context, in *EmptyReqLoan, opts ...grpc.CallOption) (*OutputGetLoan, error)
}

type loanClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanClient(cc grpc.ClientConnInterface) LoanClient {
	return &loanClient{cc}
}

func (c *loanClient) CreateLoan(ctx context.Context, in *InputCreateLoan, opts ...grpc.CallOption) (*OutputCreateLoan, error) {
	out := new(OutputCreateLoan)
	err := c.cc.Invoke(ctx, "/packets.Loan/CreateLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanClient) GetLoans(ctx context.Context, in *EmptyReqLoan, opts ...grpc.CallOption) (*OutputGetLoan, error) {
	out := new(OutputGetLoan)
	err := c.cc.Invoke(ctx, "/packets.Loan/GetLoans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServer is the server API for Loan service.
// All implementations must embed UnimplementedLoanServer
// for forward compatibility
type LoanServer interface {
	CreateLoan(context.Context, *InputCreateLoan) (*OutputCreateLoan, error)
	GetLoans(context.Context, *EmptyReqLoan) (*OutputGetLoan, error)
	mustEmbedUnimplementedLoanServer()
}

// UnimplementedLoanServer must be embedded to have forward compatible implementations.
type UnimplementedLoanServer struct {
}

func (UnimplementedLoanServer) CreateLoan(context.Context, *InputCreateLoan) (*OutputCreateLoan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoan not implemented")
}
func (UnimplementedLoanServer) GetLoans(context.Context, *EmptyReqLoan) (*OutputGetLoan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoans not implemented")
}
func (UnimplementedLoanServer) mustEmbedUnimplementedLoanServer() {}

// UnsafeLoanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServer will
// result in compilation errors.
type UnsafeLoanServer interface {
	mustEmbedUnimplementedLoanServer()
}

func RegisterLoanServer(s grpc.ServiceRegistrar, srv LoanServer) {
	s.RegisterService(&Loan_ServiceDesc, srv)
}

func _Loan_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputCreateLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Loan/CreateLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServer).CreateLoan(ctx, req.(*InputCreateLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loan_GetLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReqLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServer).GetLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Loan/GetLoans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServer).GetLoans(ctx, req.(*EmptyReqLoan))
	}
	return interceptor(ctx, in, info, handler)
}

// Loan_ServiceDesc is the grpc.ServiceDesc for Loan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packets.Loan",
	HandlerType: (*LoanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoan",
			Handler:    _Loan_CreateLoan_Handler,
		},
		{
			MethodName: "GetLoans",
			Handler:    _Loan_GetLoans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocs/loan.proto",
}
