// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protocs/loan.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputCreateLoan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoanId    string `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Amount    int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Tenure    string `protobuf:"bytes,3,opt,name=tenure,proto3" json:"tenure,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *InputCreateLoan) Reset() {
	*x = InputCreateLoan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_loan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputCreateLoan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCreateLoan) ProtoMessage() {}

func (x *InputCreateLoan) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_loan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCreateLoan.ProtoReflect.Descriptor instead.
func (*InputCreateLoan) Descriptor() ([]byte, []int) {
	return file_protocs_loan_proto_rawDescGZIP(), []int{0}
}

func (x *InputCreateLoan) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *InputCreateLoan) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InputCreateLoan) GetTenure() string {
	if x != nil {
		return x.Tenure
	}
	return ""
}

func (x *InputCreateLoan) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type OutputCreateLoan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OutputCreateLoan) Reset() {
	*x = OutputCreateLoan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_loan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputCreateLoan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputCreateLoan) ProtoMessage() {}

func (x *OutputCreateLoan) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_loan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputCreateLoan.ProtoReflect.Descriptor instead.
func (*OutputCreateLoan) Descriptor() ([]byte, []int) {
	return file_protocs_loan_proto_rawDescGZIP(), []int{1}
}

func (x *OutputCreateLoan) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OutputCreateLoan) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_loan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_loan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_protocs_loan_proto_rawDescGZIP(), []int{2}
}

type OutputGetLoan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*InputCreateLoan `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *OutputGetLoan) Reset() {
	*x = OutputGetLoan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_loan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputGetLoan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputGetLoan) ProtoMessage() {}

func (x *OutputGetLoan) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_loan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputGetLoan.ProtoReflect.Descriptor instead.
func (*OutputGetLoan) Descriptor() ([]byte, []int) {
	return file_protocs_loan_proto_rawDescGZIP(), []int{3}
}

func (x *OutputGetLoan) GetUsers() []*InputCreateLoan {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_protocs_loan_proto protoreflect.FileDescriptor

var file_protocs_loan_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x79, 0x0a,
	0x0f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x61, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4d, 0x0a, 0x10, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x61, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x32, 0x84, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x43, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x6f, 0x61, 0x6e, 0x1a, 0x19, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x61, 0x6e,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x61, 0x6e, 0x73, 0x12, 0x11,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x61, 0x6e, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocs_loan_proto_rawDescOnce sync.Once
	file_protocs_loan_proto_rawDescData = file_protocs_loan_proto_rawDesc
)

func file_protocs_loan_proto_rawDescGZIP() []byte {
	file_protocs_loan_proto_rawDescOnce.Do(func() {
		file_protocs_loan_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocs_loan_proto_rawDescData)
	})
	return file_protocs_loan_proto_rawDescData
}

var file_protocs_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocs_loan_proto_goTypes = []interface{}{
	(*InputCreateLoan)(nil),  // 0: packets.InputCreateLoan
	(*OutputCreateLoan)(nil), // 1: packets.OutputCreateLoan
	(*EmptyReq)(nil),         // 2: packets.EmptyReq
	(*OutputGetLoan)(nil),    // 3: packets.OutputGetLoan
}
var file_protocs_loan_proto_depIdxs = []int32{
	0, // 0: packets.OutputGetLoan.users:type_name -> packets.InputCreateLoan
	0, // 1: packets.User.CreateLoan:input_type -> packets.InputCreateLoan
	2, // 2: packets.User.GetLoans:input_type -> packets.EmptyReq
	1, // 3: packets.User.CreateLoan:output_type -> packets.OutputCreateLoan
	3, // 4: packets.User.GetLoans:output_type -> packets.OutputGetLoan
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocs_loan_proto_init() }
func file_protocs_loan_proto_init() {
	if File_protocs_loan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocs_loan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputCreateLoan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocs_loan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputCreateLoan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocs_loan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocs_loan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputGetLoan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocs_loan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocs_loan_proto_goTypes,
		DependencyIndexes: file_protocs_loan_proto_depIdxs,
		MessageInfos:      file_protocs_loan_proto_msgTypes,
	}.Build()
	File_protocs_loan_proto = out.File
	file_protocs_loan_proto_rawDesc = nil
	file_protocs_loan_proto_goTypes = nil
	file_protocs_loan_proto_depIdxs = nil
}
