// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protocs/transaction.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputCreateTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *InputCreateTransaction) Reset() {
	*x = InputCreateTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputCreateTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputCreateTransaction) ProtoMessage() {}

func (x *InputCreateTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputCreateTransaction.ProtoReflect.Descriptor instead.
func (*InputCreateTransaction) Descriptor() ([]byte, []int) {
	return file_protocs_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *InputCreateTransaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OutputCreateTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OutputCreateTransaction) Reset() {
	*x = OutputCreateTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocs_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputCreateTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputCreateTransaction) ProtoMessage() {}

func (x *OutputCreateTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protocs_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputCreateTransaction.ProtoReflect.Descriptor instead.
func (*OutputCreateTransaction) Descriptor() ([]byte, []int) {
	return file_protocs_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *OutputCreateTransaction) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OutputCreateTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protocs_transaction_proto protoreflect.FileDescriptor

var file_protocs_transaction_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x54,
	0x0a, 0x17, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x67, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x58, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x20, 0x2e, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protocs_transaction_proto_rawDescOnce sync.Once
	file_protocs_transaction_proto_rawDescData = file_protocs_transaction_proto_rawDesc
)

func file_protocs_transaction_proto_rawDescGZIP() []byte {
	file_protocs_transaction_proto_rawDescOnce.Do(func() {
		file_protocs_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocs_transaction_proto_rawDescData)
	})
	return file_protocs_transaction_proto_rawDescData
}

var file_protocs_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocs_transaction_proto_goTypes = []interface{}{
	(*InputCreateTransaction)(nil),  // 0: packets.InputCreateTransaction
	(*OutputCreateTransaction)(nil), // 1: packets.OutputCreateTransaction
}
var file_protocs_transaction_proto_depIdxs = []int32{
	0, // 0: packets.Transaction.CreateTransaction:input_type -> packets.InputCreateTransaction
	1, // 1: packets.Transaction.CreateTransaction:output_type -> packets.OutputCreateTransaction
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocs_transaction_proto_init() }
func file_protocs_transaction_proto_init() {
	if File_protocs_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocs_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputCreateTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocs_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputCreateTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocs_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocs_transaction_proto_goTypes,
		DependencyIndexes: file_protocs_transaction_proto_depIdxs,
		MessageInfos:      file_protocs_transaction_proto_msgTypes,
	}.Build()
	File_protocs_transaction_proto = out.File
	file_protocs_transaction_proto_rawDesc = nil
	file_protocs_transaction_proto_goTypes = nil
	file_protocs_transaction_proto_depIdxs = nil
}
